### ISSUE TITLE
deploying lattice in a private vpc without elastic ip

### ISSUE THREAD

**Issue by sergueif** [cloudfoundry-incubator/lattice#144]
Hi I'm trying to setup a Lattice for internal apps within my org. I think myself and others in similar position would benefit from a cleaner way of doing what the following amounts to:

```
terraform apply
# in aws console, rip out the elastic ip (disassociate)
vim /var/lattice/setup/lattice-environment #on lattice-brain
SYSTEM_DOMAIN=10.117.128.56.xip.io #private ip
service restart receptor
service restart trafficcontroller
```

Maybe there's a way to plug a variable in terraform for SYSTEM_DOMAIN? Or some easy modification to lattice itself that I can do in a fork?

**Comment by menicosia** [comment]
Hi @sergueif,

That change was introduced to Lattice from the community, and it seems pretty useful. The big win we get out of it is that you can suspend the VMs when you finish up for the evening, and spin them back up the following morning without re-targeting. (This'll be especially useful when Condenser is enabled, you won't have to re-target-blob as well.)

It seems unlikely that anyone who uses AWS is likely to object to the small fee incurred by an Elastic IP, so I don't think the right choice is to turn it off entirely. Would it make better sense to be able to change the routability of an Elastic IP, so that it's not open to the entire Internet? I could review with the team, but I think that would generally be a better level of security -- although we'll try to figure out if it's something we can apply across all clouds.

What do you think?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by sergueif** [comment]
Well, I ended up just completely reconfiguring the terraform resources to accomodate the private vpc setup. You can close this issue if you're not sure how exactly to package up this concern.

**Comment by menicosia** [comment]
Hi @sergueif,

Well, like all feature requests and bugs, we've automatically created a story for this in our [product backlog](https://www.pivotaltracker.com/n/projects/1183596). I think I understand the nature of the request pretty well, I am not as confident that we can make it easily configurable via Terraform. But Terraform is evolving pretty rapidly.

So I tell you what - I'll close this issue now, but keep the feature request on our Backlog. If we think of a good way to make this easy, we'll update the story. If it's something the community can do easily, we'll mark it community as well. Otherwise, we'll prioritize it accordingly for our own team to (eventually) get to it.

Seem OK? As always, you're welcome to re-open this issue if you think I've missed something.

---
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by menicosia** [comment]
Oh, I forgot to include a link to the specific story, sorry!

[99055152](https://www.pivotaltracker.com/story/show/99055152)
