### ISSUE TITLE
error submitting build... already submitted

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/lattice#166]
I provided the wrong buildpack and the wrong path when building my droplet.

```
$ ltc build-droplet dora go --path=.
Submitted build of dora
08/10 11:40:35.69 [BUILD|0] Successfully created container
Build failed: Downloading failed
```

When I try again, I get an error
```
$ cd dora/

$ ltc build-droplet dora ruby --path=.
Error submitting build of dora: build-droplet-dora has already been submitted

$ ltc list-droplets
Droplet		Created At	Size

```

Now what do I do?

**Comment by shalako** [comment]
Diego eventual consistency at play here. 

```
$ ltc list
------------------------------= Apps =-------------------------------
No apps to display.

------------------------------= Tasks =------------------------------
Task Name		Cell ID		Status		Result		Failure Reason
build-droplet-dora	cell-01		COMPLETED	N/A		N/A


$ ltc list
------------------------------= Apps =-------------------------------
No apps to display.

------------------------------= Tasks =------------------------------
No tasks to display.


$ ltc build-droplet dora ruby --path=.
Submitted build of dora
08/10 11:50:59.48 [BUILD|0] Successfully created container
08/10 11:51:11.13 [BUILD|0] -------> Buildpack version 1.6.2
...
```

**Comment by menicosia** [comment]
Just following up,

This is due to the fact that we submit builds with a predictable task name, `build-droplet-FOO` so that the user can simultaneously follow logs of the build process without having to figure out a GUID name or other.

Unfortunately, Diego does not reap tasks immediately, so in the case of a typo'd buildpack or broken app, you need to wait a few minutes to try again.

Alternatively, you can brute-force tell Diego to wipe out all task information, but this is Not Recommended outside of a Dev context:
> curl -L http://192.168.11.11:4001/v2/keys/v1/task/?recursive=true -XDELETE

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by damon-pivotal** [comment]
That curl is really dangerous. You can almost always use `ltc cancel-task build-droplet-xxx` (if it's running) or `ltc delete-task build-droplet-xxx` (if it's completed).
