### ISSUE TITLE
Support for OSv

### ISSUE THREAD

**Issue by sirinath** [cloudfoundry-incubator/lattice#180]
http://osv.io/

**Comment by menicosia** [comment]
Hi @sirinath,

I don't think any of the projects we depend on have plans for OSv. I think, overall, we're focusing this kind of brain power on solving slightly different problems: https://www.cloudfoundry.org/garden-and-runc/

I'm going to close this issue, since it's not something we can reasonably deliver. As always, you are welcome to re-open or create a new issue should you feel that we've missed something important!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
