### ISSUE TITLE
Unable to connect to lattice

### ISSUE THREAD

**Issue by pradp** [cloudfoundry-incubator/lattice#192]
I'm running lattice instance using vagrant and virtual box in windows. In the same host machine I'm running another Ubuntu virtual machine where ltc is installed. I'm trying the below ways to connect from ubuntu to the lattice instance but it is failing

```
Direct

ltc target 192.168.11.11
Error verifying target: Get http://receptor.192.168.11.11/v1/desired_lrps: dial tcp: lookup receptor.192.168.11.11: no such host


Ping works fine to 192,168.11.11
```
```
xip.io

ltc target 192.168.11.11.xip.io
Could not connect to the droplet store.


But the error message comes after a long time. 
```

```
dns

ltc target lattice.dev
Error verifying target: Get http://receptor.lattice.dev/v1/desired_lrps: dial tcp 127.0.53.53:80: connection refused


Ping works fine from Ubuntu on "lattice.dev
```

**Comment by Sacro** [comment]
Passing by as I watch GitHub for "127.0.53.53" issues,

You don't own lattice.dev and therefore don't control its DNS, please don't use it, you're getting that IP to warn you to fix things.

**Comment by davidwadden** [comment]
I think the `lattice.dev` is a red herring there.  If you haven't gone through setting up a custom resolver on OS X to handle the **.dev** resolution requests, as @Sacro points out, you're going to pick up the new NS record that Google [bought](http://www.theregister.co.uk/2015/03/13/google_developer_gtld_domain_icann/) and see some unexpected results.

For one, you absolutely need to be using the `xip.io` suffix above.

It may be simpler to run `ltc` on the vagrant box itself rather than try to do this with two machines.  It should work to copy the linux `ltc` binary into the folder you `vagrant up` from, and then `vagrant ssh` into the box and access that `ltc` binary on `/vagrant`. 

You should be able to run something like `curl -v http://receptor.192.168.11.11.xip.io/v1/desired_lrps` on the same machine you plan on running `ltc`.

**Comment by davidwadden** [comment]
@Sacro we're working on getting rid of our `.dev` dependency :fist: google

We now support `ltc target local.lattice.cf`  (requires `LATTICE_SYSTEM_DOMAIN=local.lattice.cf vagrant up` on [**v0.5.0**](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.5.0)) which might replace needing to use dnsmasq at all.

We also don't yet support Windows deployments.  Keep an eye on [[#98709384](https://www.pivotaltracker.com/story/show/98709384)] for support for that.

Closing this issue.
