### ISSUE TITLE
terraform should not depend on local files to install

### ISSUE THREAD

**Issue by littleidea** [cloudfoundry-incubator/lattice#205]
Terraform for cloud providers is using provisioner "file" for some relatively large files.

All these files should be pulled from s3 or something that isn't constrained by the speed of local wifi.

**Comment by davidwadden** [comment]
I've prioritized [[#101313546](https://www.pivotaltracker.com/story/show/101313546)] for us to review.  This hasn't been possible since we needed the ability to run Terraform with a local build for CI and there's very little flexibility on "conditional" resources and provisioners.

With the recent move to [Concourse](https://ci.lattice.cf), we can take another look whether this is feasible now, though.  I agree that Lattice should work better over slow network links.

**Comment by lexsys27** [comment]
+1 for this feature. It took 1 hour to deploy Lattice on AWS yesterday over 3G link

**Comment by davidwadden** [comment]
This is ready for all our terraform platforms and is available in our latest [nightly bundle](https://lattice.s3.amazonaws.com/nightly/index.html).  This will land in our forthcoming [**v0.5.0**](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.5.0) release.  

Thanks for your feedback!
