### ISSUE TITLE
Redis won't start after machine reboot

### ISSUE THREAD

**Issue by amaltson** [cloudfoundry-incubator/lattice#208]
I've been playing with running the Docker Hub Redis container on Lattice. I was pleasantly surprised that when I `ltc rm redis` and would `ltc create` it again all my data was still there. Then I decided to check how Lattice behaves after a machine reboot, and now it looks like Redis lost the data and doesn't start up correctly anymore.

```
$ ltc create redis redis --run-as-root --tcp-routes 6379:6379 --monitor-port 6379
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 6379
No working directory specified, using working directory from the image metadata...
Working directory is:
/data
Monitoring the app on port 6379...
No start command specified, using start command from the image metadata...
Start command is:
/entrypoint.sh redis-server
Creating App: redis

redis is now running.
App is reachable at:
<custom-domain>:6379
$ redis-cli -h <custom-domain>
<custom-domain>:6379> get x
Error: Server closed the connection
(4.21s)
<custom-domain>:6379> get x
Error: Server closed the connection
(3.00s)
<custom-domain>:6379>
$ ltc ls
------------------------------= Apps =-------------------------------
App Name	Instances	DiskMB		MemoryMB	Route
redis		0/1		0		128		<custom-domain>:6379 => 6379
```

The other strange part is I can't seem to remove the redis image anymore.

```
$ ltc rm redis
Removing redis...
$ ltc rm redis
Removing redis...
Error stopping redis: redis is not started.
$ ltc ls
------------------------------= Apps =-------------------------------
App Name	Instances	DiskMB		MemoryMB	Route
redis		1/0		0		0

------------------------------= Tasks =------------------------------
No tasks to display.
```

Any help would be greatly appreciated. Thank you.

**Edit**

I was eventually able to remove the redis instance, so that part seems to be fine. Even with redis removed, spinning it up again I can't connect anymore :disappointed:

**Comment by davidwadden** [comment]
`redis` has some issues shutting down.

what you experienced was:
1. ran `ltc rm redis`
  - updates desired state to 0 instances
  - redis keeps running because it ignores "nice" requests to shut down
1. re-started `ltc cr redis redis`
  - updates desired state to 1 instance
  - at this point, gives up trying to shut down `redis` because it still has the 1 running from before

persistence is not supported yet, although it's a hotly-requested feature.

also, it might be the tcp-router having issues.  try and run `ltc status redis` to find the container port (something like 60011) and run `redis-cli -h 192.168.11.11:60011`

also, try changing the external bind port on the tcp-routes to something else each time you restart redis,  e.g., 6380 6381 or something.  we are investigating some issues related to tcp-router [[#103287032](https://www.pivotaltracker.com/story/show/103287032)]

**Comment by amaltson** [comment]
@davidwadden running on a difference external tcp-route seemed to do the trick and Redis did come back after restarting the machine. Now it did lose it's data, but as you mentioned this is expected. Thank you!

**Comment by davidwadden** [comment]
thanks @amaltson  -- we're working on getting tcp-router updated which should resolve this issue
