### ISSUE TITLE
Permission denied when creating app

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry-incubator/lattice#64]
Freshly minted lattice 0.2.1 on virtualbox and  linux host:

```
$ ltc create grace lattice/grace
Error fetching image metadata: open /etc/docker/certs.d/index.docker.io: permission denied
```

Of course that file on the host is owned by root, but why does ltc need it?

**Comment by davidwadden** [comment]
This was previously reported in https://github.com/pivotal-cf-experimental/lattice-cli/issues/15

This problem is specific to the docker 1.5.0 package provided on the custom apt repository

`ltc` uses the docker api [docker repo](https://github.com/docker/docker) to fetch metadata for a docker image, which in turn relies on the docker installed locally (or boot2docker on OS X)

**Comment by davidwadden** [comment]
I'm assuming you worked past this.  Another contributor submitted docker/docker#11927 to address the underlying root cause.  Docker 1.6 was released recently, I haven't checked whether this was addressed in that **apt-get** package.

Closing this issue as it looks resolved.  Please re-open if you have additional concerns.
