### ISSUE TITLE
Improve the local developer experience

### ISSUE THREAD

**Issue by onsi** [cloudfoundry-incubator/lattice#71]
Lattice makes it dead-simple to spin up a clustered container orchestration environment.  Our theme for the next iteration of work will revolve around improving the developer experience.

In particular, we want to tackle this problem:

> As a developer, how do I get the source code I'm working on locally up and running in Lattice?

We hope to take a two-pronged approach and are open to community feedback:

1. For developers employing a Docker-oriented flow we believe that bundling Lattice with a preconfigured private Docker registry and Docker daemon will allow users to build and push images to Lattice then turn around and `ltc create` applications based on those images.

2. For developers who simply want to get their application running on Lattice and don't need to package things up as Docker images we plan on bringing the elegant simplicity of `cf push` to Lattice.

  In particular, we intend to make it easy and efficient to push source code to Lattice, specify a CF/Heroku Buildpack, and create a compiled artifact (in CF terms, a droplet).  This compiled artifact can then be run on any Lattice installation.  Eventually we could even make it possible to create a Docker image based on the compiled artifact.  This would turn Lattice into a general purpose compiler for the cloud.

I wanted to open up this issue to get feedback and thoughts around this two-pronged approach.

**Comment by spencergibb** [comment]
@onsi I like both, obviously the `ltc push myapp.jar` is the more elegant solution, but also more difficult.  I would be happy with 1 until 2 is done.

**Comment by LaynePeng** [comment]
Like 1st one, but not sure 2nd one is valueable or not. Say if introduce app stagercapability into Lattice, is that means something like stager project in CF?

**Comment by philwebb** [comment]
+1 for option 2, `ltc push app.jar` would be a real bonus for Java developers if it can be made fast enough.

**Comment by svennela** [comment]
+1 for option 2, ltc push app.jar + (app.war, need to update docker file to run tomcat and deploy as root.).

**Comment by mstine** [comment]
Option 3:

Create IDE plugins that allow me to "run my app on Lattice." This would be the logical equivalent of clicking "play" in Eclipse or IDEA that would compile my code and make it available for Lattice to download into a container image. 

- Lattice would need a rootFS that already contains the appropriate JRE. Beyond that, no further changes would be required. This could be accomplished via a Docker image now as a stop gap.

- The IDE plugin would need to compile the bits, and make the appropriate packaged app structure available for download via an internal HTTP server. The plugin would then craft an appropriate Diego LRP that would choose the aforementioned rootFS and the HTTP server as a download target.

- Exposing appropriate ports to connect the IDE debugger to the running Java process on Lattice would also be trivial.

I've vetted these ideas with both @onsi (for Diego/Lattice) and @aclement (for IDE tooling), and both thought these ideas seemed feasible. 

Of course the developer using the IDE would not be exposed to any of these internal technical details. There would simply be an alternate run target in the IDE that would need to know the location of the Lattice install.

**Comment by ragsns** [comment]
+1 for option 2 as well. At some point if I replace ltc with cf it should just work.

**Comment by aclement** [comment]
Thinking more on it, if you turn option (3) around, it becomes something very similar to what @philwebb and I were playing with for rapid development on CF. Instead of the IDE offering a place to get the files from, you have the server/container offer an endpoint to send the files too.  In the scenario we played with we would push the initial app (could be just a  shell of an app) to the destination and it would have a port open to receive updates. As classes are developed/compiled in the IDE (or dependencies changed) the updates are sent to the destination to update the filesystem there, and then either the app notices the change and restarts itself or there is a way to prod it to say 'restart'. Similarly to option (3) all hidden behind a run button for the app.

Our solution was boot specific because we could support the restart mechanic easily there, and we were also able to do some smarts such that we recognized which was application code and which 'infrastructure' code and using a split class loader mechanic ensure we only reloaded the application code (ensuring the app restart was very quick).  But even without using Spring Boot, a way to update the destination FS in a container without needing to rebuild an image and re-push it would improve the turnaround time on testing changes.  (Obviously if you could mount any external disk location in a container, that would work too in the local lattice case).

Just some thoughts.

**Comment by onsi** [comment]
A question about approach 1.  We can fairly easily run a private docker registry on Lattice.  It would be preferable to avoid also running a Docker daemon.  Does anyone have an opinion on this?

It would mean that to push a docker image to the Lattice registry you would need to have a Docker daemon running somewhere (on OS X/windows this would presumably be running on Boot2Docker).

**Comment by amaltson** [comment]
:+1: to 1. and 2, I'm getting really interested in Lattice and this will push me to deploy it.

@onsi don't mind that approach to 1., we do that already in house. Works fine.

**Comment by menicosia** [comment]
This has been delivered as of: [v0.3.0](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.3.0)

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
