### ISSUE TITLE
Openstack support for Lattice

### ISSUE THREAD

**Issue by davebotelho** [cloudfoundry-incubator/lattice#84]
Is there a plan to add Openstack as a supported provider for Lattice?  I've got Terraform working for Openstack already and was looking to try out lattice.

Thanks,
Dave

**Comment by onsi** [comment]
No short-term plans, no.  PRs welcome!

**Comment by LaynePeng** [comment]
BTW, I have create a heat template to deploy Lattice in OpenStack, and planning to try to add it to Magnum.

**Comment by onsi** [comment]
awesome @LaynePeng !  let us know if we can help!

**Comment by matjohn2** [comment]
I have a working TF module for Openstack. Planning to raise PR today. Relies on neutron & VIP's and uses the openstack default provider released in Terraform 0.4. -M

**Comment by matjohn2** [comment]
.. @LaynePeng  @onsi @davebotelho Testing and feedback would be really appreciated if you have the time!

**Comment by davebotelho** [comment]
Cool. I’d like to try it out.

**Comment by matjohn2** [comment]
https://github.com/cloudfoundry-incubator/lattice/pull/108 :+1:

**Comment by menicosia** [comment]
Hi @davebotelho @LaynePeng, (/cc @matjohn2, @ajlanghorn)

We've released Version 0.2.5 of Lattice, which includes an OpenStack Terraform module. I've been keeping this issue open until that release.

https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.5

Normally, I let people know that they should feel welcome to re-open an issue should our solution not fully address the problem. However, in this case, "OpenStack support" is very broad. We now include an OpenStack module, but it is **community supported.** We do not have a Continuous Integration pipeline to validate that it work across releases. Worse, because there is no single OpenStack to support, your mileage may vary. Rather than keep this issue hanging around, in the future, I'd suggest to please open new issues with specific details about the OpenStack environment in question.

Sound OK? Closing this issue, but please feel free to share your feedback.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by matjohn2** [comment]
I think that is fair given the broad number of environments under then 'openstack' umbrella

Thanks for integrating this, will make adoption of lattice for developers on openstack a hopefully painless experience!

Matt

Sent from a mobile device.

On 4 Jun 2015, at 20:13, "Marco Nicosia" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @davebotelho<https://github.com/davebotelho> @LaynePeng<https://github.com/LaynePeng>, (/cc @matjohn2<https://github.com/matjohn2>, @ajlanghorn<https://github.com/ajlanghorn>)

We've released Version 0.2.5 of Lattice, which includes an OpenStack Terraform module. I've been keeping this issue open until that release.

https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.5

Normally, I let people know that they should feel welcome to re-open an issue should our solution not fully address the problem. However, in this case, "OpenStack support" is very broad. We now include an OpenStack module, but it is community supported. We do not have a Continuous Integration pipeline to validate that it work across releases. Worse, because there is no single OpenStack to support, your mileage may vary. Rather than keep this issue hanging around, in the future, I'd suggest to please open new issues with specific details about the OpenStack environment in question.

Sound OK? Closing this issue, but please feel free to share your feedback.

Marco Nicosia
Product Manager
Pivotal Software, Inc.
