### ISSUE TITLE
ltc build fails on OS X 10.10.3 with Go go1.4.2 darwin/amd64

### ISSUE THREAD

**Issue by gerhard** [cloudfoundry-incubator/lattice#97]
Using the scripts/install from #95:
```
scripts/install
# github.com/cloudfoundry-incubator/lattice/ltc/app_examiner/command_factory
app_examiner/command_factory/app_examiner_command_factory.go:54: unknown cli.Command field 'Aliases' in struct literal
app_examiner/command_factory/app_examiner_command_factory.go:75: unknown cli.Command field 'Aliases' in struct literal
app_examiner/command_factory/app_examiner_command_factory.go:99: unknown cli.Command field 'Aliases' in struct literal
# github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory
app_runner/command_factory/app_runner_command_factory.go:144: unknown cli.Command field 'Aliases' in struct literal
app_runner/command_factory/app_runner_command_factory.go:175: unknown cli.Command field 'Aliases' in struct literal
app_runner/command_factory/app_runner_command_factory.go:194: unknown cli.Command field 'Aliases' in struct literal
app_runner/command_factory/app_runner_command_factory.go:214: unknown cli.Command field 'Aliases' in struct literal
app_runner/command_factory/app_runner_command_factory.go:228: unknown cli.Command field 'Aliases' in struct literal
# github.com/cloudfoundry-incubator/lattice/ltc/config/command_factory
config/command_factory/config_command_factory.go:30: unknown cli.Command field 'Aliases' in struct literal
# github.com/cloudfoundry-incubator/lattice/ltc/integration_test/command_factory
integration_test/command_factory/integration_test_command_factory.go:34: unknown cli.Command field 'Aliases' in struct literal
# github.com/cloudfoundry-incubator/lattice/ltc/logs/command_factory
logs/command_factory/logs_command_factory.go:33: unknown cli.Command field 'Aliases' in struct literal
logs/command_factory/logs_command_factory.go:46: unknown cli.Command field 'Aliases' in struct literal
```

Thought godep might help, but came across a different error:
```
godep restore
package github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/Users/gerhard/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
godep: restore: exit status 1
```

Can someone try installing this on a clean go OS X env?

**Comment by davidwadden** [comment]
those errors look like it's trying to use an old version of codegangsta/cli,  he recently added the .Aliases field and we switched over to using that instead of .ShortName.  so the best guess i have is that somehow the godeps aren't actually being used, and another copy of (an older revision of) codegangsta/cli is sitting in your GOPATH somehow

did you follow the instructions from the [development readme](https://github.com/cloudfoundry-incubator/lattice/blob/master/development-readme.md) (clones diego-release and then lattice repo underneath of that) or the [ltc readme](https://github.com/cloudfoundry-incubator/lattice/tree/master/ltc) (uses `go get -d` and then `godep` or `GOPATH=$GOPATH/src/github.com/cloudfoundry-incubator/lattice/ltc/Godeps/_workspace:$GOPATH go install github.com/cloudfoundry-incubator/lattice/ltc` to switch in the vendored dependencies at compile-time.

`godep restore` will throw that error about dockerversion, but it's usually not a problem.  `godep` has some issues with submodules if you follow the development-readme, though.

why don't you try setting up a new GOPATH and following the instructions from ltc/README -  `go get -d`, `scripts/install` and let us know what that does?

**Comment by gerhard** [comment]
The only codegagsta/cli which I had was `~/go/src/github.com/cloudfoundry-incubator/lattice/ltc/Godeps/_workspace/src/github.com/codegangsta/cli` but I was still getting the .Aliases error.

Will follow the ltc Development readme closely and get back.

**Comment by davidwadden** [comment]
yeah, that should kind of remove the complexity of godeps in the interim, but it adds the complexity there's now cf-release and diego-release and all their submodules that need to be set at the proper revision with lattice, which was why we added godeps in the first place to avoid all that.

we're not sure how we got it to reproduce in the first place, and when we looked at codegangsta/cli, it was the newer version that supported Aliases.

**Comment by menicosia** [comment]
@gerhard ping, checking to see if there's any hope that we can close this issue.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by gerhard** [comment]
I went down the pre-built binary path in the end, happy to close for now. Cheers!
