### ISSUE TITLE
vSphere support for Lattice

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-incubator/lattice#98]
Analogous to the asked Openstack support, will there by any vSphere support? If not, where do I find some details regarding the implementation for the required steps to include vSphere as an additional CPI?

**Comment by menicosia** [comment]
Hi @jhiemer,

We don't have a near-term plan to support vSphere. Because of this, I do have a story ([92643338](https://www.pivotaltracker.com/story/show/92643338)) in the backlog. The purpose of the story is to explain at a high level what we're doing when we deploy to either Vagrant or the public clouds. It's not a very complex process, so the idea is that vSphere users such as yourselves should be able to follow a manual process without needing to crawl through glass.

The story is tentatively scheduled to be worked on some time between the v0.2.4 and v0.2.5 releases. Please let me know if this would be sufficient for your needs?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by jhiemer** [comment]
Hi @menicosia,
thanks for your reply. Indeed this story covers what I am seeking for. The only thing that made me struggle was `Multi-VM Terraform-like deploys are out of scope.`. Having a multi-VM setup would be a large benefit, for massiv parallel execution of calculations for example.

My question here is: as far as I can see, lattices uses quite a subset of components known from CF. Why didn't you reuse BOSH to manage deployment of lattice?

Regards,
Johannes

**Comment by menicosia** [comment]
Hi @jhiemer,

I'm following up on this because we've recently finished up work on the above story, [92643338](https://www.pivotaltracker.com/story/show/92643338). I'm sorry I neglected to follow up on your second question till now. You can see the manual install instructions [here](https://github.com/cloudfoundry-incubator/lattice/blob/develop/docs/manual-install.md).

Sorry this response is kind of long, but I wanted you to understand where we're coming from:

The answer re: both scaling and BOSH is partially philosophical, partially pragmatic. Lattice's primary goal is to be a very easy way to explore advanced features that are coming soon to Cloud Foundry. At the moment, that's primarily Diego and its ability to deploy Docker images. Only the minimal infrastructure possible is bolted on to enable that - gorouter and Loggregator/Doppler. BOSH, in particular, is out of scope - it's an amazing beast that has a pretty massive learning curve. It's not necessary for the primary goal, so it's not included.

Lattice is recognizing a secondary goal as well: As we work on the 'condenser' epic, Lattice will evolve into a developer on-ramp to Cloud Foundry. App developers will be able to develop/test/iterate on a minimal environment (especially on localhost) and producing artifacts that are compatible with CF. Right now, several projects are focused on giving Developers access to CF-like experiences which will hopefully guide them to Cloud Foundry proper in the future. There's a lot of work to make this happen, and it's important to get to it as soon as possible.

Coincidentally, with the introduction of Terraform, Lattice is turning out to be a compelling way to run these components at scale. This turns out to be cool - in some scenarios, it's possible that Lattice is all a small startup would need to conduct production operations.

But as you notice, without lightweight tools like Terraform, there's no easy way to deploy to a (private) cloud. There are lots of heavyweight tools to accomplish this - BOSH being among them. Given goals 1 and 2, the work to leverage BOSH takes Lattice in the wrong direction. The primary focus is the enabling potential Cloud Foundry developer. Cloud Foundry's focus is the web app developer - deploying at scale isn't necessary for Lattice's users. They can upgrade to Cloud Foundry for that.

In the case of vSphere, there's no Terraform provider (yet). As a very small team, anything that complicates or distracts from that goal has to be carefully considered. This is a long winded way of saying that documenting manual install instructions made sense for enabling the non-cloud-enabled Developer (no access to Vagrant or Terraform). But if you scan the instructions, you can see that they're already turning into code-as-documentation, like adding specific environment variables to files. There are nuances to how all of that changes when you deploy across VMs, and that's not something we're likely to prioritize soon. Worse, the more docs such as these, the higher the likelihood they'll go stale as the underlying tech evolves.

I'm going to close this issue, but please feel free to continue the conversation; any decision that's true today doesn't necessarily remain true in the future.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
